services:
  django:
    build:
      dockerfile: docker/django/Dockerfile
      target: django_with_entrypoint
      args:
        - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - OPENAI_API_KEY=${GITHUB_API_KEY}
      - AUTH_ENABLED=${AUTH_ENABLED}
      - APP_BASE_URL=${APP_BASE_URL}
    volumes:
      - ./django:/code
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - redis
      - postgresql


  postgresql:
    image: public.ecr.aws/docker/library/postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: public.ecr.aws/docker/library/redis:7-alpine

  celery:
    build:
      dockerfile: docker/django/Dockerfile
      target: django
      args:
        - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
    command: celery -A core worker -l info
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - OPENAI_API_KEY=${GITHUB_API_KEY}
      - AUTH_ENABLED=${AUTH_ENABLED}
      - APP_BASE_URL=${APP_BASE_URL}
    volumes:
      - ./django:/code
    depends_on:
      - redis
      - postgresql
    dns:
      - 178.22.122.100
      - 185.51.200.2

  nextjs:
      build:
        context: .
        dockerfile: docker/nextjs/Dockerfile
        args:
          NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      command: npm run start
      environment:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      ports:
        - "${NEXTJS_PORT}:3000"


volumes:
  postgres_data: